export const SAMPLES = [
  {
    id: 1,
    Country: "Afghanistan",
    WellName: "BU HASA-19",
    WellCode: "FPCW_102432",
    Province: "Atlantic Ocean",
    ProspectBasin: "Kwanza Basin",
    SampleCode: "FPC_937230",
    SampleType: "ROCK",
    Type: "ROCK",
    Depthinterval: "7700-7720",
    Topdepth: "7700",
    Basedepth: "7720",
  },
  {
    id: 2,
    Country: "Albania",
    WellName: "FERMA-30",
    WellCode: "FPCW_432432",
    Province: "Atlantic Ocean",
    ProspectBasin: "Kwanza Basin",
    SampleCode: "FPC_265884",
    SampleType: "OIL",
    Type: "OIL",
    Depthinterval: "8700-9000",
    Topdepth: "8700",
    Basedepth: "9000",
  },
  {
    id: 3,
    Country: "Bahamas",
    WellName: "NPI-15",
    WellCode: "FPCW_789488",
    Province: "Atlantic Ocean",
    ProspectBasin: "Kwanza Basin",
    SampleCode: "FPC_784567",
    SampleType: "CHEMICAL",
    Type: "CHEMICAL",
    Depthinterval: "4000-5000",
    Topdepth: "4000",
    Basedepth: "5000",
  },
  {
    id: 4,
    Country: "Bahrain",
    WellName: "AWALI-128",
    WellCode: "FPCW_434532",
    Province: "Atlantic Ocean",
    ProspectBasin: "Kwanza Basin",
    SampleCode: "FPC_456767",
    SampleType: "GAS",
    Type: "GAS",
    Depthinterval: "6000-7000",
    Topdepth: "6000",
    Basedepth: "7000",
  },
  {
    id: 5,
    Country: "Barbados",
    WellName: "BARBADOS RID",
    WellCode: "FPCW_889488",
    Province: "Atlantic Ocean",
    ProspectBasin: "Kwanza Basin",
    SampleCode: "FPC_256767",
    SampleType: "MUD",
    Type: "MUD",
    Depthinterval: "3000-4000",
    Topdepth: "3000",
    Basedepth: "4000",
  },
  {
    id: 6,
    Country: "Canada",
    WellName: "100-04-13-056",
    WellCode: "FPCW_102253",
    Province: "Atlantic Ocean",
    ProspectBasin: "Kwanza Basin",
    SampleCode: "FPC_346767",
    SampleType: "RECENT",
    Type: "RECENT",
    Depthinterval: "2000-3000",
    Topdepth: "2000",
    Basedepth: "3000",
  },
  {
    id: 7,
    Country: "Albania",
    WellName: "FERMA-30",
    WellCode: "FPCW_532432",
    Province: "Atlantic Ocean",
    ProspectBasin: "Kwanza Basin",
    SampleCode: "FPC_365884",
    SampleType: "SOLID",
    Type: "SOLID",
    Depthinterval: "8700-9000",
    Topdepth: "8700",
    Basedepth: "9000",
  },
];
